[package]
name = "os/zombiegame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Fusion = "elttob/fusion@0.3.0"
PartCache = "andremhpra/partcache@1.0.0"
TableUtil = "sleitnick/table-util@1.2.1"
ProfileStore = "detourious/loleris-profilestore@1.0.0"
Janitor = "howmanysmall/janitor@1.18.3"
Packet = "sjdinsd/packet@0.1.91"
Hitbox = "breezy1214/hitbox@4.1.2"
Signal = "sleitnick/signal@2.0.3"
Timer = "sleitnick/timer@1.1.2"
Fastcastredux = "ulferno/fastcastredux@13.2.1"

[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"
