[package]
name = "os/zombiegame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Fusion = "elttob/fusion@0.3.0"
PartCache = "andremhpra/partcache@1.0.0"
TableUtil = "sleitnick/table-util@1.2.1"

FusionComponents = "virtualbutfake/fusion-components@0.1.18"
themeFramework = "virtualbutfake/theme-framework@0.1.6"
fusionUtils = "virtualbutfake/fusion-utils@0.1.2"
tailwind = "virtualbutfake/tailwind@0.1.1"

[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"
