[package]
name = "os/zombiegame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Fusion = "elttob/fusion@0.3.0"
PartCache = "andremhpra/partcache@1.0.0"
TableUtil = "sleitnick/table-util@1.2.1"
ProfileStore = "detourious/loleris-profilestore@1.0.0"
Janitor = "howmanysmall/already-janitor@1.16.0"
Packet = "sjdinsd/packet@0.1.91"

[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"
